config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#home'

  resources :books, only: [:index, :show]

  resources :authors, only: :index do
    member do
      get 'books'
    end
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :authors_books
  has_many :books, through: :authors_books

  validates :first_name, :last_name, presence: true
end

app/models/authors_book.rb
class AuthorsBook < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :authors_books
  has_many :authors, through: :authors_books

  validates :title, :published_at, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  expose(:authors) { Author.includes(:books).order(:last_name) }
  expose(:author)
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  expose(:books) { Book.includes(:authors).page(params[:page]).per_page(5).order(:title) }
  expose(:book)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/books.html.haml
%h1= author.decorate.name
%img{ src: author.avatar }
%p= author.biography
= render 'books/books_list', books: author.books

app/views/authors/index.html.haml
%h1 Authors
- authors.each do |author|
  %img{ src: author.avatar }
  %ul
    %li= link_to author.decorate.name, books_author_path(author)
    %li= author.decorate.formatted_books_titles

app/views/books/_books_list.haml
- books.each do |book|
  %img{ src: book.cover }
  %ul
    %li= link_to book.decorate.title_with_date, book_path(book)
    %li= book.decorate.formatted_authors

app/views/books/index.html.haml
%h1 Books
= will_paginate books
= render 'books_list', books: books

app/views/books/show.html.haml
%h1= book.decorate.title_with_date
%ul
- book.authors.each do |author|
  %li= link_to author.decorate.name, books_author_path(author)
%img{ src: book.cover }
%p= book.description

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  = content_tag :div, msg, class: name

app/views/layouts/_navigation.html.haml
%ul
  %li= link_to 'Home',    root_path
  %li= link_to 'Books',   books_path
  %li= link_to 'Authors', authors_path

- if user_signed_in?
  %ul
    %li= link_to 'Log out', destroy_user_session_path, method: :delete
    %li= link_to 'Account', edit_user_registration_path
- else
  %ul
    %li= link_to 'Sign up', new_user_registration_path
    %li= link_to 'Log in',  new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Books Review Web Application
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main
      = render 'layouts/messages'
      = yield

app/views/welcome/home.html.haml
%h1 Welcome on Books Review Web Application
%p It's nice to meet you :)